# Generated by Django 4.1.2 on 2022-10-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latearrival', '0003_alter_latearrival_date_arrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latearrival',
            name='observations',
            field=models.CharField(blank=True, default='NINGUNA', max_length=50, null=True),
        ),
    ]
